/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cinema.ticket;

import javax.swing.ButtonModel;



/**
 *
 * @author yann
 */
public class Ticket_sale_form extends javax.swing.JFrame {

    /**
     * Creates new form Ticket_sale_form
     */
    public Ticket_sale_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filmGroup = new javax.swing.ButtonGroup();
        typeGroup = new javax.swing.ButtonGroup();
        mvList1 = new javax.swing.JRadioButton();
        mvList2 = new javax.swing.JRadioButton();
        mvList3 = new javax.swing.JRadioButton();
        mvList4 = new javax.swing.JRadioButton();
        mvList5 = new javax.swing.JRadioButton();
        mvList6 = new javax.swing.JRadioButton();
        typeList1 = new javax.swing.JRadioButton();
        typeList2 = new javax.swing.JRadioButton();
        typeList3 = new javax.swing.JRadioButton();
        typeList4 = new javax.swing.JRadioButton();
        timeBox = new javax.swing.JComboBox<>();
        priceForm = new javax.swing.JTextField();
        amountForm = new javax.swing.JTextField();
        totalForm = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        movieType = new javax.swing.JLabel();
        typeTicket = new javax.swing.JLabel();
        showTime = new javax.swing.JLabel();
        amountTicket = new javax.swing.JLabel();
        priceTitle = new javax.swing.JLabel();
        totalTitle = new javax.swing.JLabel();
        btnDelete1 = new javax.swing.JButton();
        btnProccess1 = new javax.swing.JButton();
        aSpinner = new javax.swing.JSpinner();
        btnPrint = new javax.swing.JButton();
        txt_area = new javax.swing.JTextArea();

        filmGroup.add(mvList1);
        filmGroup.add(mvList2);
        filmGroup.add(mvList3);
        filmGroup.add(mvList4);
        filmGroup.add(mvList5);
        filmGroup.add(mvList6);

        typeGroup.add(typeList1);
        typeGroup.add(typeList2);
        typeGroup.add(typeList3);
        typeGroup.add(typeList4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CVG Cinemas");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(58, 45, 83));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 140, 199));
        setMaximizedBounds(new java.awt.Rectangle(540, 504, 504, 504));
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(540, 504));
        setPreferredSize(new java.awt.Dimension(540, 504));
        setSize(new java.awt.Dimension(540, 504));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mvList1.setText("John Wick 5");
        mvList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvList1ActionPerformed(evt);
            }
        });
        getContentPane().add(mvList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        mvList2.setText("Moana");
        mvList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvList2ActionPerformed(evt);
            }
        });
        getContentPane().add(mvList2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        mvList3.setText("The last of us");
        mvList3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvList3ActionPerformed(evt);
            }
        });
        getContentPane().add(mvList3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        mvList4.setText("Transformers");
        mvList4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvList4ActionPerformed(evt);
            }
        });
        getContentPane().add(mvList4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        mvList5.setText("Re: 7");
        mvList5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvList5ActionPerformed(evt);
            }
        });
        getContentPane().add(mvList5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        mvList6.setText("Vikings");
        mvList6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvList6ActionPerformed(evt);
            }
        });
        getContentPane().add(mvList6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        typeList1.setText("Regular 2D");
        typeList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeList1ActionPerformed(evt);
            }
        });
        getContentPane().add(typeList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        typeList2.setText("Regular 3D");
        typeList2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeList2ActionPerformed(evt);
            }
        });
        getContentPane().add(typeList2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        typeList3.setText("Premiere");
        typeList3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeList3ActionPerformed(evt);
            }
        });
        getContentPane().add(typeList3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        typeList4.setText("Premiere 4D");
        typeList4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeList4ActionPerformed(evt);
            }
        });
        getContentPane().add(typeList4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        timeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{ "13.45", "14.15", "16.20", "20.30", "21.15" }));
        timeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeBoxActionPerformed(evt);
            }
        });
        getContentPane().add(timeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 110, 30));

        priceForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFormActionPerformed(evt);
            }
        });
        getContentPane().add(priceForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 110, 30));

        amountForm.setEditable(false);
        amountForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFormActionPerformed(evt);
            }
        });
        getContentPane().add(amountForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 60, 30));

        totalForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalFormActionPerformed(evt);
            }
        });
        getContentPane().add(totalForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 110, 30));

        title.setFont(new java.awt.Font("Unispace", 1, 20)); // NOI18N
        title.setForeground(new java.awt.Color(204, 0, 153));
        title.setText("CVG CINEMAS");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, 47));

        movieType.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        movieType.setText("Movie :");
        getContentPane().add(movieType, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        typeTicket.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        typeTicket.setText("Ticket :");
        getContentPane().add(typeTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        showTime.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        showTime.setText("Showtime :");
        getContentPane().add(showTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        amountTicket.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        amountTicket.setText("Amount :");
        getContentPane().add(amountTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        priceTitle.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        priceTitle.setText("Price Ticket :");
        getContentPane().add(priceTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        totalTitle.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        totalTitle.setText("Total :");
        getContentPane().add(totalTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        btnDelete1.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete1.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete1.setText("Cancel");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 90, 30));

        btnProccess1.setBackground(new java.awt.Color(0, 255, 204));
        btnProccess1.setText("Proccess");
        btnProccess1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProccess1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnProccess1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 90, 30));

        aSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                aSpinnerStateChanged(evt);
            }
        });
        getContentPane().add(aSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 20, 30));

        btnPrint.setBackground(new java.awt.Color(204, 204, 0));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 90, 30));

        txt_area.setColumns(20);
        txt_area.setRows(5);
        getContentPane().add(txt_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 200, 210));

        setSize(new java.awt.Dimension(556, 612));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void mvList6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvList6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mvList6ActionPerformed

    private void mvList4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvList4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mvList4ActionPerformed
  
    private void mvList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvList1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mvList1ActionPerformed

    private void mvList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvList2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mvList2ActionPerformed

    private void mvList3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvList3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mvList3ActionPerformed
 
    private void mvList5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvList5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mvList5ActionPerformed

    private void typeList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeList1ActionPerformed
        // set the price to Rp. 30,000
        int price = 30000;
        // set the priceForm text field to display "Rp. 30,000"
        priceForm.setText("Rp. " + price);
    }//GEN-LAST:event_typeList1ActionPerformed

    private void typeList2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeList2ActionPerformed
        // set the price to Rp. 50,000
        int price = 50000;
        // set the priceForm text field to display "Rp. 50,000"
        priceForm.setText("Rp. " + price);
    }//GEN-LAST:event_typeList2ActionPerformed

    private void typeList3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeList3ActionPerformed
        // set the price to Rp. 120,000
        int price = 120000;
        // set the priceForm text field to display "Rp. 120,000"
        priceForm.setText("Rp. " + price);
    }//GEN-LAST:event_typeList3ActionPerformed

    private void typeList4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeList4ActionPerformed
         // set the price to Rp. 150,000
        int price = 150000;
        // set the priceForm text field to display "Rp. 150,000"
        priceForm.setText("Rp. " + price);
    }//GEN-LAST:event_typeList4ActionPerformed

    private void timeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeBoxActionPerformed
        String selectedTime = (String) timeBox.getSelectedItem();
        System.out.println("Selected time: " + selectedTime);
       // TODO add your handling code here:
    }//GEN-LAST:event_timeBoxActionPerformed

    private void priceFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFormActionPerformed

    private void amountFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFormActionPerformed

    private void totalFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalFormActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        priceForm.setText("");
        amountForm.setText("");
        totalForm.setText("");
        
       filmGroup.clearSelection();
       typeGroup.clearSelection();
        
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnProccess1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProccess1ActionPerformed
        // TODO add your handling code here:
        int price = Integer.parseInt(priceForm.getText().replaceAll("\\D+",""));
        int amount = Integer.parseInt(amountForm.getText());
        int result = price * amount;
        
        totalForm.setText("Rp. " + result );

    }//GEN-LAST:event_btnProccess1ActionPerformed

    private void aSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_aSpinnerStateChanged
        // TODO add your handling code here:
        String spinner = "changed";
        Integer myInt = (Integer)aSpinner.getValue();
        if (myInt < 0) {
            myInt = 0;
            aSpinner.setValue(myInt);
    }
    spinner = myInt.toString();
    amountForm.setText(spinner);
    }//GEN-LAST:event_aSpinnerStateChanged

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
         ButtonModel selectedButton = filmGroup.getSelection();
    if(selectedButton != null) {
        String selectedMovie = selectedButton.getActionCommand();
        txt_area.setText("Film yang Anda pilih: " + selectedMovie);
    } else {
        txt_area.setText("Tidak ada film yang dipilih.");
    }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket_sale_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket_sale_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket_sale_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket_sale_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ticket_sale_form form = new Ticket_sale_form();
                form.setSize(625, 638); // menentukan ukuran frame
                form.setLocationRelativeTo(null); // menentukan posisi frame di tengah layar
                form.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner aSpinner;
    private javax.swing.JTextField amountForm;
    private javax.swing.JLabel amountTicket;
    public javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnProccess1;
    private javax.swing.ButtonGroup filmGroup;
    private javax.swing.JLabel movieType;
    private javax.swing.JRadioButton mvList1;
    private javax.swing.JRadioButton mvList2;
    private javax.swing.JRadioButton mvList3;
    private javax.swing.JRadioButton mvList4;
    private javax.swing.JRadioButton mvList5;
    private javax.swing.JRadioButton mvList6;
    private javax.swing.JTextField priceForm;
    private javax.swing.JLabel priceTitle;
    private javax.swing.JLabel showTime;
    private javax.swing.JComboBox<String> timeBox;
    private javax.swing.JLabel title;
    private javax.swing.JTextField totalForm;
    private javax.swing.JLabel totalTitle;
    private javax.swing.JTextArea txt_area;
    private javax.swing.ButtonGroup typeGroup;
    private javax.swing.JRadioButton typeList1;
    private javax.swing.JRadioButton typeList2;
    private javax.swing.JRadioButton typeList3;
    private javax.swing.JRadioButton typeList4;
    private javax.swing.JLabel typeTicket;
    // End of variables declaration//GEN-END:variables
}
